window.MASUSI_CONFIG = {
  SUPABASE_URL: "PASTE_YOUR_SUPABASE_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_YOUR_SUPABASE_ANON_KEY_HERE",
  STORAGE_BUCKET: "resort-assets",
  DEFAULT_RESORT_NAME: "Masusi Farm Resort"
};
