/* Masusi Farm Resort V2.1
   Separate Cottage + Ligo and Room booking workflows.
   Booking numbers/codes are generated by Supabase.
*/

const v21RenderCurrent = renderCurrent;
renderCurrent = async function(){
  if(state.currentView==='cottage-bookings') return renderBookingTypePage('cottage_swim');
  if(state.currentView==='room-bookings') return renderBookingTypePage('room');
  return v21RenderCurrent();
};

const v21Navigate = navigate;
navigate = function(view){
  state.currentView=view;
  $$('.view').forEach(v=>v.classList.remove('active'));
  $(`#view-${view}`)?.classList.add('active');
  $$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  $('#sidebar').classList.remove('open');
  const titles={
    dashboard:'Dashboard',live:'Live Rooms & Cottages',bookings:'All Bookings',
    'cottage-bookings':'Cottage + Ligo Bookings','room-bookings':'Room Bookings',
    availability:'Availability Calendar',rooms:'Rooms',cottages:'Cottages',guests:'Guests',barcode:'Barcode Scanner',billing:'Billing',payments:'Payments',invoices:'Invoices',expenses:'Expenses',damages:'Damages',repairs:'Repairs',inventory:'Inventory',pos:'Store / POS',services:'Services Library',reports:'Reports',users:'Users',audit:'Audit Logs',settings:'Settings'
  };
  $('#pageTitle').textContent=titles[view]||'Masusi Farm Resort';
  renderCurrent();
};

function v21Settings(){
  return {
    adult:Number(state.settings.adult_swim_rate||0),
    kid:Number(state.settings.kid_swim_rate||0),
    senior:Number(state.settings.senior_discount||0),
    pwd:Number(state.settings.pwd_discount||0)
  };
}
function calcCottageBooking({cottage_id,adults=0,kids=0,babies=0,seniors=0,pwd=0}){
  const c=state.cache.cottages.find(x=>x.id===cottage_id); const s=v21Settings();
  adults=Number(adults||0);kids=Number(kids||0);babies=Number(babies||0);seniors=Number(seniors||0);pwd=Number(pwd||0);
  const sr=Math.min(seniors,adults), pw=Math.min(pwd,Math.max(adults-sr,0)), regular=Math.max(adults-sr-pw,0);
  const cottage=Number(c?.base_rate||0);
  const swim=(regular*s.adult)+(sr*s.adult*(1-s.senior/100))+(pw*s.adult*(1-s.pwd/100))+(kids*s.kid);
  return {cottage,swim,total:cottage+swim,regular,sr,pw,babies};
}
function calcRoomBooking({room_id,check_in_date,check_out_date,adults=0,kids=0}){
  const r=state.cache.rooms.find(x=>x.id===room_id);
  let nights=1;
  if(check_in_date&&check_out_date){
    const a=new Date(check_in_date+'T00:00:00'),b=new Date(check_out_date+'T00:00:00');
    nights=Math.max(1,Math.round((b-a)/86400000));
  }
  const chargeable=Number(adults||0)+Number(kids||0), extra=Math.max(0,chargeable-Number(r?.capacity||0));
  const room=Number(r?.base_rate||0)*nights, extraFee=Number(r?.extra_person_rate||0)*extra*nights;
  return {nights,room,extra,extraFee,total:room+extraFee};
}

async function renderBookingTypePage(type){
  await getTable('bookings');
  const isCottage=type==='cottage_swim';
  const rows=state.cache.bookings.filter(b=>(b.booking_type||((b.room_id)?'room':'cottage_swim'))===type);
  const id=isCottage?'cottage-bookings':'room-bookings';
  const title=isCottage?'Cottage + Ligo Bookings':'Room Bookings';
  $(`#view-${id}`).innerHTML=`
    <div class="section-head"><div><p class="eyebrow">${isCottage?'DAY USE / SWIMMING':'OVERNIGHT / ROOM'}</p><h2>${title}</h2></div></div>
    <div class="table-panel">
      <div class="table-toolbar">
        <input id="${id}Search" class="grow" type="search" placeholder="Search guest, booking no. or booking code...">
        <input id="${id}Month" type="month" value="${currentMonth()}">
        <select id="${id}Status"><option value="">All status</option><option>pending</option><option>confirmed</option><option>checked_in</option><option>checked_out</option><option>cancelled</option><option>no_show</option></select>
        <button class="btn btn-soft" id="${id}Print">Print Month</button>
        <button class="btn btn-primary" id="${id}Add">Add ${isCottage?'Cottage + Ligo':'Room'} Booking</button>
      </div>
      <div class="table-scroll"><table class="data-table"><thead><tr><th>Booking No.</th><th>Guest</th><th>${isCottage?'Cottage':'Room'}</th><th>Check-in</th><th>Pax</th><th>Base</th><th>Paid</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody id="${id}Body"></tbody></table></div>
    </div>`;
  const draw=()=>{
    const q=$(`#${id}Search`).value.toLowerCase().trim(),m=$(`#${id}Month`).value,st=$(`#${id}Status`).value;
    const filtered=rows.filter(b=>{
      const hay=`${b.booking_number||''} ${b.booking_code||b.barcode||''} ${b.guest_name||''} ${b.contact_number||''}`.toLowerCase();
      return hay.includes(q)&&(!m||String(b.check_in_date||b.booking_date||'').slice(0,7)===m)&&(!st||b.status===st);
    });
    $(`#${id}Body`).innerHTML=filtered.length?filtered.map(b=>{
      const unit=isCottage?cottageById(b.cottage_id):roomById(b.room_id), pax=Number(b.adults||0)+Number(b.kids||0)+Number(b.babies||0);
      return `<tr><td><strong>${esc(b.booking_number||'Auto')}</strong><br><small>${esc(b.booking_code||b.barcode||'')}</small></td><td>${esc(b.guest_name||'—')}<br><small>${esc(b.contact_number||'')}</small></td><td>${esc(unit?.name||unit?.unit_number||'—')}</td><td>${fmtDate(b.check_in_date)}</td><td>${pax}</td><td>${money(b.base_amount||0)}</td><td>${money(b.paid_amount||0)}</td><td>${money(b.balance||0)}</td><td><span class="badge">${esc(b.status||'pending')}</span></td><td><div class="row-actions"><button data-v21-view="${b.id}">View</button><button data-v21-code="${b.id}">Barcode / QR</button><button data-v21-edit="${b.id}">Edit</button><button data-v21-pay="${b.id}">Payment</button></div></td></tr>`;
    }).join(''):`<tr><td colspan="10" class="empty-state">No ${title.toLowerCase()} found.</td></tr>`;
    $$('[data-v21-view]').forEach(x=>x.onclick=()=>openRecord('bookings',x.dataset.v21View));
    $$('[data-v21-code]').forEach(x=>x.onclick=()=>openCodesModal(state.cache.bookings.find(b=>b.id===x.dataset.v21Code)));
    $$('[data-v21-edit]').forEach(x=>x.onclick=()=>openBookingV21(type,x.dataset.v21Edit));
    $$('[data-v21-pay]').forEach(x=>x.onclick=()=>openPaymentModal(state.cache.bookings.find(b=>b.id===x.dataset.v21Pay)));
  };
  $(`#${id}Search`).oninput=draw;$(`#${id}Month`).onchange=draw;$(`#${id}Status`).onchange=draw;$(`#${id}Add`).onclick=()=>openBookingV21(type);$(`#${id}Print`).onclick=()=>printElementView(id);draw();
}

function openBookingV21(type,id=null){
  const isCottage=type==='cottage_swim', b=id?state.cache.bookings.find(x=>x.id===id):null;
  const cottages=state.cache.cottages.filter(x=>x.is_active!==false&&!['maintenance','damaged','inactive'].includes(x.status));
  const rooms=state.cache.rooms.filter(x=>x.is_active!==false&&!['maintenance','damaged','inactive'].includes(x.status));
  const unitOptions=(isCottage?cottages:rooms).map(x=>`<option value="${x.id}" ${(isCottage?b?.cottage_id:b?.room_id)===x.id?'selected':''}>${esc(x.name||x.unit_number)} · ${money(x.base_rate||0)} · Capacity ${x.capacity||0}</option>`).join('');
  openModal({title:id?`Edit ${isCottage?'Cottage + Ligo':'Room'} Booking`:`New ${isCottage?'Cottage + Ligo':'Room'} Booking`,eyebrow:id?`BOOKING ${b?.booking_number||''}`:'AUTO BOOKING NUMBER',wide:true,body:`
    ${b ? `<div class="panel full" style="margin-bottom:14px"><div class="panel-head"><h3>Booking Barcode / QR</h3><button type="button" class="btn btn-soft" id="v22ShowBookingCode">View / Print Barcode & QR</button></div><p><strong>${esc(b.booking_code||b.barcode||'Generating...')}</strong></p><p class="tiny muted">This booking scan code is separate from the Booking Number and can be used for payment, lookup and check-in.</p></div>` : `<div class="panel full" style="margin-bottom:14px"><h3>Booking Barcode / QR</h3><p class="tiny muted">A unique Booking Scan Code, Barcode and QR Code will be generated automatically after you save this booking.</p></div>`}
    <form id="v21BookingForm" class="modal-form">
      <label>Guest / Client Name<input name="guest_name" required value="${esc(b?.guest_name||'')}"></label>
      <label>Contact Number<input name="contact_number" value="${esc(b?.contact_number||'')}"></label>
      <label>Check-in Date<input name="check_in_date" type="date" required value="${esc(b?.check_in_date||today())}"></label>
      <label>Check-out Date<input name="check_out_date" type="date" required value="${esc(b?.check_out_date||(isCottage?today():''))}"></label>
      <label class="full">${isCottage?'Cottage':'Room'}<select name="unit_id" required><option value="">Select ${isCottage?'cottage':'room'}...</option>${unitOptions}</select></label>
      <label>Adults<input name="adults" type="number" min="0" value="${b?.adults??0}"></label>
      <label>Kids<input name="kids" type="number" min="0" value="${b?.kids??0}"></label>
      <label>Babies (Free)<input name="babies" type="number" min="0" value="${b?.babies??0}"></label>
      <label>Senior (included in Adults)<input name="seniors" type="number" min="0" value="${b?.seniors??0}"></label>
      <label>PWD (included in Adults)<input name="pwd" type="number" min="0" value="${b?.pwd??0}"></label>
      <label>Status<select name="status"><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="checked_in">Checked In</option><option value="checked_out">Checked Out</option><option value="cancelled">Cancelled</option><option value="no_show">No Show</option></select></label>
      <label class="full">Notes<textarea name="notes" rows="3">${esc(b?.notes||'')}</textarea></label>
    </form>
    <div id="v21Calc" class="panel" style="margin-top:14px"></div>
  `,footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v21SaveBooking">Save Booking</button>`});
  $('[data-modal-cancel]').onclick=closeModal;
  const f=$('#v21BookingForm'); if(b)f.elements.status.value=b.status||'pending';
  if(b && $('#v22ShowBookingCode')) $('#v22ShowBookingCode').onclick=()=>openCodesModal(b);
  const recalc=()=>{
    const fd=new FormData(f), data=Object.fromEntries(fd.entries());
    if(isCottage){
      const c=calcCottageBooking({cottage_id:data.unit_id,adults:data.adults,kids:data.kids,babies:data.babies,seniors:data.seniors,pwd:data.pwd});
      $('#v21Calc').innerHTML=`<div class="panel-head"><h3>Automatic Cottage + Ligo Computation</h3></div><div class="report-kpis"><div class="report-kpi"><span>Cottage Fee</span><strong>${money(c.cottage)}</strong></div><div class="report-kpi"><span>Ligo / Entrance</span><strong>${money(c.swim)}</strong></div><div class="report-kpi"><span>Baby</span><strong>FREE</strong></div><div class="report-kpi"><span>Base Total</span><strong>${money(c.total)}</strong></div></div><p class="tiny muted">Adults include Senior/PWD. Senior/PWD discounts use the percentages in Settings. Extra purchases/services are added later to the same running account.</p>`;
    }else{
      const r=calcRoomBooking({room_id:data.unit_id,check_in_date:data.check_in_date,check_out_date:data.check_out_date,adults:data.adults,kids:data.kids});
      $('#v21Calc').innerHTML=`<div class="panel-head"><h3>Automatic Room Computation</h3></div><div class="report-kpis"><div class="report-kpi"><span>Nights</span><strong>${r.nights}</strong></div><div class="report-kpi"><span>Room Fee</span><strong>${money(r.room)}</strong></div><div class="report-kpi"><span>Extra Pax</span><strong>${r.extra}</strong></div><div class="report-kpi"><span>Base Total</span><strong>${money(r.total)}</strong></div></div><p class="tiny muted">Formula: room rate × nights + extra-person rate × extra chargeable guests × nights. Babies are free for extra-person counting.</p>`;
    }
  };
  ['change','input'].forEach(ev=>f.addEventListener(ev,recalc)); recalc();
  $('#v21SaveBooking').onclick=async()=>{
    const fd=new FormData(f), d=Object.fromEntries(fd.entries());
    const adults=Number(d.adults||0),kids=Number(d.kids||0),babies=Number(d.babies||0),seniors=Number(d.seniors||0),pwd=Number(d.pwd||0);
    if(!d.guest_name.trim())return toast('Guest / client name is required.','error');
    if(!d.unit_id)return toast(`Select a ${isCottage?'cottage':'room'}.`,'error');
    if(seniors+pwd>adults)return toast('Senior + PWD cannot be greater than Adults.','error');
    const payload={booking_type:type,guest_name:d.guest_name.trim(),contact_number:d.contact_number||null,booking_date:b?.booking_date||today(),check_in_date:d.check_in_date,check_out_date:d.check_out_date,adults,kids,babies,seniors,pwd,status:d.status||'pending',notes:d.notes||null};
    if(isCottage){payload.cottage_id=d.unit_id;payload.room_id=null;}else{payload.room_id=d.unit_id;payload.cottage_id=null;}
    // Do not send booking_number/base/total/payment_status. Supabase V2.1 owns them.
    let res;
    if(id)res=await sb.from('bookings').update(payload).eq('id',id).select().single();
    else res=await sb.from('bookings').insert({...payload,created_by:state.session.user.id}).select().single();
    if(res.error)return toast(res.error.message,'error');
    closeModal();await refreshOperations();
    const savedBooking=state.cache.bookings.find(x=>x.id===res.data.id)||res.data;
    toast(`${isCottage?'Cottage + Ligo':'Room'} booking saved as ${savedBooking.booking_number}.`);
    renderBookingTypePage(type);
    // For a newly created booking, immediately show its scannable Booking Barcode + QR.
    // On edit, keep the user in the booking list.
    if(!id) setTimeout(()=>openCodesModal(savedBooking),80);
  };
}

// All Bookings should not expose booking number/status as nullable input fields anymore.
const v21ModuleConfig=moduleConfig;
moduleConfig=function(name){
  if(name==='bookings') return {table:'bookings',title:'All Bookings',date:'check_in_date',readonly:true,fields:[
    ['booking_number','Booking No.','text'],['booking_code','Booking Code','text'],['booking_type','Type','text'],['guest_name','Guest Name','text'],['contact_number','Contact','text'],['check_in_date','Check-in','date'],['check_out_date','Check-out','date'],['status','Status','text'],['total_amount','Total','number'],['paid_amount','Paid','number'],['balance','Balance','number']
  ]};
  return v21ModuleConfig(name);
};

// Settings fields should reflect database values when the settings page opens.
const v21ApplyBrand=applyBrand;
applyBrand=function(){
  v21ApplyBrand();
  const g=$('#generalSettingsForm'),r=$('#rulesSettingsForm');
  if(g){['resort_name','address','contact_number','email','invoice_footer'].forEach(k=>{if(g.elements[k])g.elements[k].value=state.settings[k]??''})}
  if(r){['adult_age','child_age','baby_age_max','senior_discount','pwd_discount','adult_swim_rate','kid_swim_rate'].forEach(k=>{if(r.elements[k])r.elements[k].value=state.settings[k]??0})}
};

// Ensure rule save updates the newly added rates too.
$('#rulesSettingsForm').onsubmit=async e=>{
  e.preventDefault(); const fd=new FormData(e.currentTarget), payload={id:1};
  for(const [k,v] of fd.entries())payload[k]=Number(v);
  const {error}=await sb.from('system_settings').upsert(payload,{onConflict:'id'});if(error)return toast(error.message,'error');
  state.settings={...state.settings,...payload};toast('Guest, discount and swimming rates saved.');
};

// V2.1 code card: Booking Number is the readable reference; Booking Code is the scan/payment/check-in code.
openCodesModal=function(b){
  if(!b)return;
  const pax=bookingPax(b.id), scanCode=b.booking_code||b.barcode||b.booking_number;
  openModal({title:'Booking Barcode / QR',eyebrow:b.booking_number,wide:true,body:`
    <div class="dashboard-grid">
      <div class="panel">
        <h3>Booking Number</h3>
        <p style="font-size:20px"><strong>${esc(b.booking_number)}</strong></p>
        <p class="tiny muted">Readable reservation reference. Use this for reports, invoice and manual search.</p>
      </div>
      <div class="panel">
        <h3>Booking Scan Code</h3>
        <p style="font-size:20px"><strong>${esc(scanCode)}</strong></p>
        <div style="display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin-top:12px">
          <div id="bookingQr" style="background:#fff;padding:8px;border:1px solid var(--line);border-radius:10px"></div>
          <svg id="bookingBarcode" style="max-width:100%"></svg>
        </div>
        <p class="tiny muted">Scan this code for payment, booking lookup and check-in. It is generated automatically for both Cottage + Ligo and Room bookings.</p>
      </div>
    </div>
    <div class="table-panel" style="margin-top:14px">
      <div class="panel-head" style="padding:14px 14px 0"><h3>Pax Codes</h3><span class="muted tiny">${pax.length} pax</span></div>
      <div class="table-scroll"><table class="data-table"><thead><tr><th>Pax</th><th>Type</th><th>Pax Code</th><th>Status</th></tr></thead><tbody>
        ${pax.length?pax.map(p=>`<tr><td>${esc(paxDisplayName(p))}</td><td>${esc(p.pax_type)}</td><td><strong>${esc(p.code)}</strong></td><td>${esc(p.access_status)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty-state">Pax codes will appear here after pax records are generated.</td></tr>'}
      </tbody></table></div>
    </div>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Close</button><button class="btn btn-soft" id="copyBookingCodeBtn">Copy Code</button><button class="btn btn-primary" id="printCodesBtn">Print Barcode / QR</button>`});
  $('[data-modal-cancel]').onclick=closeModal;
  try{
    new QRCode($('#bookingQr'),{text:scanCode,width:150,height:150});
    JsBarcode('#bookingBarcode',scanCode,{format:'CODE128',displayValue:true,height:64,margin:8});
  }catch(e){ toast('Barcode renderer could not load. Check your internet connection for the barcode libraries.','error'); }
  $('#copyBookingCodeBtn').onclick=async()=>{
    try{await navigator.clipboard.writeText(scanCode);toast('Booking Scan Code copied.');}
    catch{toast(`Booking Scan Code: ${scanCode}`);}
  };
  $('#printCodesBtn').onclick=()=>window.print();
};

// Scan accepts Booking Number or Booking Scan Code.
scanBarcode=async function(){
  const code=$('#barcodeInput').value.trim(); if(!code)return;
  await refreshOperations();
  const pax=(state.cache.pax||[]).find(p=>p.code===code && p.access_status!=='cancelled');
  if(pax){state.activeScanPax=pax;return handlePaxScan(pax)}
  const booking=state.cache.bookings.find(b=>b.booking_number===code||b.booking_code===code||b.barcode===code);
  if(booking)return openBookingScanResult(booking);
  const {data:bc}=await sb.from('barcodes').select('*').eq('code',code).eq('is_active',true).maybeSingle();
  if(bc?.booking_id){const b=state.cache.bookings.find(x=>x.id===bc.booking_id);if(b)return openBookingScanResult(b)}
  $('#barcodeResult').innerHTML=`<div class="empty-state"><strong>Code not found</strong><p>${esc(code)}</p><small>Scan a Pax Code or Booking Scan Code, or manually enter the Booking Number.</small></div>`;
};
$('#barcodeSearchBtn').onclick=scanBarcode;
$('#barcodeInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();scanBarcode()}};



/* ============================================================
   MASUSI FARM RESORT V2.4
   PAX CODE MANAGER + CORRECT CHECK-IN SCAN FLOW
   Booking: auto-generated scan code
   Pax: manual/scan by default, optional auto-generate
   ============================================================ */

state.v24ScanTarget = null;

function v24Norm(v){ return String(v||'').trim(); }
function v24FindPaxByCode(code){
  const c=v24Norm(code).toLowerCase();
  return (state.cache.pax||[]).find(p=>v24Norm(p.code).toLowerCase()===c && p.access_status!=='cancelled');
}
function v24FindBookingByCode(code){
  const c=v24Norm(code).toLowerCase();
  return (state.cache.bookings||[]).find(b=>
    [b.booking_number,b.booking_code,b.barcode].some(v=>v24Norm(v).toLowerCase()===c)
  );
}
function v24RandomPaxCode(){
  const s=crypto.getRandomValues(new Uint32Array(2));
  return `MFR-PAX-${s[0].toString(36).toUpperCase()}${s[1].toString(36).toUpperCase()}`.slice(0,24);
}

// ---------- Override main scanner ----------
scanBarcode = async function(){
  const el=$('#barcodeInput'), code=v24Norm(el?.value);
  if(!code)return;
  await refreshOperations();

  const pax=v24FindPaxByCode(code);
  if(pax){ state.activeScanPax=pax; return handlePaxScanV24(pax); }

  const booking=v24FindBookingByCode(code);
  if(booking) return openBookingScanResult(booking);

  const {data:bc}=await sb.from('barcodes').select('*').ilike('code',code).eq('is_active',true).maybeSingle();
  if(bc?.booking_id){
    const b=state.cache.bookings.find(x=>x.id===bc.booking_id);
    if(b)return openBookingScanResult(b);
  }

  $('#barcodeResult').innerHTML=`<div class="empty-state">
    <strong>Code not found</strong>
    <p>${esc(code)}</p>
    <small>You can scan a Booking Scan Code, Booking Number, or a Pax Code assigned in Edit Booking.</small>
  </div>`;
  el?.select();
};
if($('#barcodeSearchBtn')) $('#barcodeSearchBtn').onclick=scanBarcode;
if($('#barcodeInput')) $('#barcodeInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();scanBarcode()}};

// ---------- PAX MANAGER ----------
async function openPaxManagerV24(booking){
  await refreshOperations();
  const pax=autoSortRows('pax',(state.cache.pax||[]).filter(p=>p.booking_id===booking.id && p.access_status!=='cancelled'));

  openModal({
    title:'Pax / Companion Barcode Manager',
    eyebrow:booking.booking_number,
    wide:true,
    body:`
      <div class="panel" style="margin-bottom:14px">
        <div class="panel-head">
          <div>
            <h3>${esc(booking.guest_name||'Guest')}</h3>
            <p class="muted">${esc(booking.booking_type||'booking')} · ${esc(booking.booking_number)}</p>
          </div>
          <button class="btn btn-primary" id="v24AddPaxBtn">Add Companion / Pax</button>
        </div>
        <p class="tiny muted">
          Booking barcode is generated automatically. Pax codes are manual by default.
          For each pax you can scan your own printed barcode, type a code, or use Auto Generate.
        </p>
      </div>

      <div class="table-panel">
        <div class="table-scroll">
          <table class="data-table">
            <thead><tr>
              <th>#</th><th>Pax</th><th>Type</th><th>Current Code</th><th>Status</th><th>Actions</th>
            </tr></thead>
            <tbody id="v24PaxRows">
              ${pax.length?pax.map((p,i)=>`
                <tr>
                  <td><strong>${i+1}</strong></td>
                  <td>${esc(paxDisplayName(p)||`Pax ${i+1}`)}</td>
                  <td>${esc(p.pax_type||'adult')}</td>
                  <td><strong>${esc(p.code||'NO CODE')}</strong></td>
                  <td><span class="badge">${esc(p.access_status||'not_checked_in')}</span></td>
                  <td>
                    <div class="row-actions">
                      <button data-v24-manual="${p.id}">Manual Code</button>
                      <button data-v24-scan="${p.id}">Scan Code</button>
                      <button data-v24-auto="${p.id}">Auto Generate</button>
                      ${p.code?`<button data-v24-clear="${p.id}">Clear</button>`:''}
                    </div>
                  </td>
                </tr>`).join(''):`<tr><td colspan="6" class="empty-state">No pax records yet.</td></tr>`}
            </tbody>
          </table>
        </div>
      </div>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Close</button>`
  });

  $('[data-modal-cancel]').onclick=closeModal;
  $('#v24AddPaxBtn').onclick=()=>openAddPaxV24(booking);

  $$('[data-v24-manual]').forEach(btn=>btn.onclick=()=>{
    const p=state.cache.pax.find(x=>x.id===btn.dataset.v24Manual);
    openManualPaxCodeV24(booking,p);
  });
  $$('[data-v24-scan]').forEach(btn=>btn.onclick=()=>{
    const p=state.cache.pax.find(x=>x.id===btn.dataset.v24Scan);
    openScanPaxCodeV24(booking,p);
  });
  $$('[data-v24-auto]').forEach(btn=>btn.onclick=()=>{
    const p=state.cache.pax.find(x=>x.id===btn.dataset.v24Auto);
    autoGeneratePaxCodeV24(booking,p);
  });
  $$('[data-v24-clear]').forEach(btn=>btn.onclick=()=>{
    const p=state.cache.pax.find(x=>x.id===btn.dataset.v24Clear);
    clearPaxCodeV24(booking,p);
  });
}

function openManualPaxCodeV24(booking,p){
  openModal({
    title:'Enter Pax Code',
    eyebrow:paxDisplayName(p),
    body:`<form id="v24ManualPaxForm" class="modal-form">
      <label class="full">Barcode / QR / Code
        <input name="code" autocomplete="off" value="${esc(p.code||'')}" placeholder="Example: 123456789012 or your own code" required autofocus>
      </label>
      <p class="tiny muted full">This should match the code printed on the physical barcode/QR that you will give to this pax.</p>
    </form>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v24SaveManualCode">Save Code</button>`
  });
  $('[data-modal-cancel]').onclick=()=>openPaxManagerV24(booking);
  $('#v24SaveManualCode').onclick=async()=>{
    const code=v24Norm(new FormData($('#v24ManualPaxForm')).get('code'));
    if(!code)return toast('Enter a code.','error');
    await savePaxCodeV24(booking,p,code);
  };
}

function openScanPaxCodeV24(booking,p){
  openModal({
    title:'Scan Pax Barcode',
    eyebrow:paxDisplayName(p),
    body:`<div class="scanner-panel">
      <div class="scanner-icon">▥</div>
      <h3>Scan the physical barcode now</h3>
      <p class="muted">Your Bluetooth/USB scanner should type the code below and send Enter.</p>
      <input id="v24PaxScanInput" class="barcode-input" autocomplete="off" placeholder="Waiting for scanner..." autofocus>
      <p class="tiny muted">You can also type the code manually here and press Enter.</p>
    </div>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v24UseScannedCode">Use Code</button>`
  });
  $('[data-modal-cancel]').onclick=()=>openPaxManagerV24(booking);
  const input=$('#v24PaxScanInput');
  setTimeout(()=>input?.focus(),100);
  const use=async()=>{
    const code=v24Norm(input.value);
    if(!code)return toast('Scan or enter a code first.','error');
    await savePaxCodeV24(booking,p,code);
  };
  input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();use()}};
  $('#v24UseScannedCode').onclick=use;
}

async function autoGeneratePaxCodeV24(booking,p){
  confirmModal('Auto Generate Pax Code',
    `Generate a system Pax Code for ${paxDisplayName(p)}? You can print this code later.`,
    async()=>{
      const code=v24RandomPaxCode();
      closeModal();
      await savePaxCodeV24(booking,p,code);
    }
  );
}

async function savePaxCodeV24(booking,p,code){
  // uniqueness check
  const {data:dupe}=await sb.from('booking_pax').select('id,booking_id').eq('code',code).neq('id',p.id).maybeSingle();
  if(dupe)return toast('That Pax Code is already assigned to another pax.','error');

  const {error}=await sb.from('booking_pax').update({code}).eq('id',p.id);
  if(error)return toast(error.message,'error');

  await writeAudit('update','booking_pax',p.id,`Pax code assigned/changed to ${code}`);
  await refreshOperations();
  toast('Pax code saved.');
  openPaxManagerV24(state.cache.bookings.find(x=>x.id===booking.id)||booking);
}

async function clearPaxCodeV24(booking,p){
  confirmModal('Clear Pax Code',
    `Remove the current code from ${paxDisplayName(p)}? The pax will not be scannable until a new code is assigned.`,
    async()=>{
      const {error}=await sb.from('booking_pax').update({code:null}).eq('id',p.id);
      if(error)return toast(error.message,'error');
      closeModal(); await refreshOperations(); toast('Pax code cleared.');
      openPaxManagerV24(state.cache.bookings.find(x=>x.id===booking.id)||booking);
    },true
  );
}

function openAddPaxV24(booking){
  openModal({
    title:'Add Companion / Pax',
    eyebrow:booking.booking_number,
    body:`<form id="v24AddPaxForm" class="modal-form">
      <label>Pax Type
        <select name="pax_type">
          <option value="adult">Adult</option>
          <option value="kid">Kid</option>
          <option value="baby">Baby</option>
          <option value="senior">Senior</option>
          <option value="pwd">PWD</option>
        </select>
      </label>
      <label>Name / Label
        <input name="display_name" placeholder="Optional: Juan / Pax 11">
      </label>
      <label>Code Method
        <select name="code_method" id="v24CodeMethod">
          <option value="none">No code yet</option>
          <option value="manual">Manual / Scan my own code</option>
          <option value="auto">Auto Generate</option>
        </select>
      </label>
      <label>Barcode / QR / Code
        <input name="code" id="v24AddPaxCode" autocomplete="off" placeholder="Scan or type code">
      </label>
      <p class="tiny muted full">If you choose Manual, focus the code field and scan your printed barcode. If Auto Generate, the system will create the code.</p>
    </form>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v24SaveNewPax">Add Pax</button>`
  });
  $('[data-modal-cancel]').onclick=()=>openPaxManagerV24(booking);
  $('#v24CodeMethod').onchange=e=>{
    if(e.target.value==='auto') $('#v24AddPaxCode').value=v24RandomPaxCode();
    if(e.target.value==='none') $('#v24AddPaxCode').value='';
    if(e.target.value==='manual') setTimeout(()=>$('#v24AddPaxCode').focus(),50);
  };
  $('#v24AddPaxCode').onkeydown=e=>{
    if(e.key==='Enter'){e.preventDefault();$('#v24SaveNewPax').click()}
  };
  $('#v24SaveNewPax').onclick=async()=>{
    const fd=new FormData($('#v24AddPaxForm'));
    const code=v24Norm(fd.get('code'))||null;
    if(code){
      const {data:dupe}=await sb.from('booking_pax').select('id').eq('code',code).maybeSingle();
      if(dupe)return toast('That Pax Code is already assigned.','error');
    }
    const payload={
      booking_id:booking.id,
      pax_type:fd.get('pax_type'),
      display_name:v24Norm(fd.get('display_name'))||null,
      code,
      access_status:'not_checked_in'
    };
    const {error}=await sb.from('booking_pax').insert(payload);
    if(error)return toast(error.message,'error');
    await refreshOperations(); toast('Companion/Pax added.');
    openPaxManagerV24(state.cache.bookings.find(x=>x.id===booking.id)||booking);
  };
}

// ---------- Correct scan/check-in flow ----------
async function handlePaxScanV24(p){
  const b=activeBookingForPax(p);
  if(!b)return toast('Booking for this pax was not found.','error');

  if((p.access_status||'not_checked_in')==='not_checked_in'){
    const isRoom=b.booking_type==='room'||!!b.room_id;
    if(isRoom)return openFirstRoomEntryV24(p,b);
    return openFirstCottageEntryV24(p,b);
  }

  const isRoom=b.booking_type==='room'||!!b.room_id;
  const unit=isRoom
    ? roomById(p.assigned_room_id||b.room_id)
    : cottageById(p.assigned_cottage_id||b.cottage_id);

  $('#barcodeResult').innerHTML=`<div class="report-kpis">
    <div class="report-kpi"><span>Pax</span><strong>${esc(paxDisplayName(p))}</strong></div>
    <div class="report-kpi"><span>${isRoom?'Room':'Cottage'}</span><strong>${esc(unit?.name||unit?.unit_number||'—')}</strong></div>
    <div class="report-kpi"><span>Status</span><strong>${esc(p.access_status)}</strong></div>
    <div class="report-kpi"><span>Booking</span><strong>${esc(b.booking_number)}</strong></div>
  </div>
  <div class="panel">
    <p><strong>${esc(p.code||'NO CODE')}</strong></p>
    <div class="row-actions">
      <button class="btn btn-primary" id="v24AccountBtn">Booking Account</button>
      ${p.access_status==='inside'?'<button class="btn btn-soft" id="v24OutBtn">Mark OUT</button><button class="btn btn-soft" id="v24PurchaseBtn">Add Purchase</button>':''}
      ${p.access_status==='outside'?'<button class="btn btn-primary" id="v24ReturnBtn">Mark RETURNED</button>':''}
    </div>
  </div>`;

  $('#v24AccountBtn').onclick=()=>openCottageAccount(b.id,p.id);
  if($('#v24OutBtn')) $('#v24OutBtn').onclick=()=>accessActionV24(p,'exit');
  if($('#v24ReturnBtn')) $('#v24ReturnBtn').onclick=()=>accessActionV24(p,'return');
  if($('#v24PurchaseBtn')) $('#v24PurchaseBtn').onclick=()=>openPOSForPax(p,b);
  $('#barcodeInput')?.select();
}

function openFirstCottageEntryV24(p,b){
  const options=state.cache.cottages
    .filter(c=>c.is_active!==false && !['maintenance','damaged','inactive'].includes(c.status))
    .map(c=>`<option value="${c.id}" ${b.cottage_id===c.id?'selected':''}>${esc(c.name||c.unit_number)} · Capacity ${c.capacity||'—'}</option>`).join('');

  openModal({
    title:'Assign Cottage & Check In',
    eyebrow:'FIRST PAX SCAN',
    body:`<div class="panel">
      <strong>${esc(paxDisplayName(p))}</strong>
      <p class="muted">${esc(b.booking_number)} · ${esc(b.guest_name||'Guest')}</p>
      <p>Scanned Code: <strong>${esc(p.code)}</strong></p>
    </div>
    <form id="v24FirstCottageForm" class="modal-form">
      <label class="full">Select Cottage
        <select name="cottage_id" required><option value="">Select cottage...</option>${options}</select>
      </label>
    </form>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v24ConfirmCottageCheckin">Assign & Check In</button>`
  });
  $('[data-modal-cancel]').onclick=closeModal;
  $('#v24ConfirmCottageCheckin').onclick=async()=>{
    const cottage_id=new FormData($('#v24FirstCottageForm')).get('cottage_id');
    if(!cottage_id)return toast('Select a cottage.','error');
    const now=new Date().toISOString();
    const {error}=await sb.from('booking_pax').update({
      assigned_cottage_id:cottage_id,assigned_room_id:null,
      access_status:'inside',first_check_in_at:now,last_return_at:now
    }).eq('id',p.id);
    if(error)return toast(error.message,'error');

    await sb.from('access_logs').insert({
      booking_id:b.id,pax_id:p.id,cottage_id,room_id:null,
      action:'check_in',scanned_code:p.code,performed_by:state.session.user.id
    });
    const patch={status:'checked_in'};
    if(!b.cottage_id)patch.cottage_id=cottage_id;
    await sb.from('bookings').update(patch).eq('id',b.id);

    closeModal(); await refreshOperations();
    toast(`${paxDisplayName(p)} checked in.`);
    handlePaxScanV24(state.cache.pax.find(x=>x.id===p.id));
  };
}

function openFirstRoomEntryV24(p,b){
  const room=roomById(b.room_id);
  if(!room){
    openModal({
      title:'Room Not Assigned',eyebrow:'CHECK-IN BLOCKED',
      body:`<p>This Room Booking has no room selected. Edit the booking first and assign a room.</p>`,
      footer:`<button class="btn btn-primary" data-modal-cancel>Close</button>`
    });
    $('[data-modal-cancel]').onclick=closeModal;
    return;
  }

  openModal({
    title:'Confirm Room Check-In',
    eyebrow:'FIRST PAX SCAN',
    body:`<div class="report-kpis">
      <div class="report-kpi"><span>Pax</span><strong>${esc(paxDisplayName(p))}</strong></div>
      <div class="report-kpi"><span>Room</span><strong>${esc(room.name||room.unit_number)}</strong></div>
      <div class="report-kpi"><span>Booking</span><strong>${esc(b.booking_number)}</strong></div>
      <div class="report-kpi"><span>Code</span><strong>${esc(p.code)}</strong></div>
    </div>
    <p class="muted">This pax will check in to the room already assigned to the Room Booking.</p>`,
    footer:`<button class="btn btn-soft" data-modal-cancel>Cancel</button><button class="btn btn-primary" id="v24ConfirmRoomCheckin">Check In</button>`
  });
  $('[data-modal-cancel]').onclick=closeModal;
  $('#v24ConfirmRoomCheckin').onclick=async()=>{
    const now=new Date().toISOString();
    const {error}=await sb.from('booking_pax').update({
      assigned_room_id:b.room_id,assigned_cottage_id:null,
      access_status:'inside',first_check_in_at:now,last_return_at:now
    }).eq('id',p.id);
    if(error)return toast(error.message,'error');

    await sb.from('access_logs').insert({
      booking_id:b.id,pax_id:p.id,room_id:b.room_id,cottage_id:null,
      action:'check_in',scanned_code:p.code,performed_by:state.session.user.id
    });
    await sb.from('bookings').update({status:'checked_in'}).eq('id',b.id);
    closeModal(); await refreshOperations(); toast(`${paxDisplayName(p)} checked in to ${room.name||room.unit_number}.`);
    handlePaxScanV24(state.cache.pax.find(x=>x.id===p.id));
  };
}

async function accessActionV24(p,action){
  const b=activeBookingForPax(p); if(!b)return;
  const now=new Date().toISOString(), isExit=action==='exit';
  const patch=isExit
    ? {access_status:'outside',last_exit_at:now}
    : {access_status:'inside',last_return_at:now};

  const {error}=await sb.from('booking_pax').update(patch).eq('id',p.id);
  if(error)return toast(error.message,'error');

  await sb.from('access_logs').insert({
    booking_id:b.id,pax_id:p.id,
    cottage_id:p.assigned_cottage_id||b.cottage_id||null,
    room_id:p.assigned_room_id||b.room_id||null,
    action:isExit?'exit':'return',
    scanned_code:p.code,performed_by:state.session.user.id
  });
  await refreshOperations();
  toast(isExit?'Pax marked OUT.':'Pax marked RETURNED.');
  handlePaxScanV24(state.cache.pax.find(x=>x.id===p.id));
}

// ---------- Hook Pax Manager into booking UI ----------
document.addEventListener('click',e=>{
  const btn=e.target.closest('[data-v24-pax-manager]');
  if(!btn)return;
  const b=state.cache.bookings.find(x=>x.id===btn.dataset.v24PaxManager);
  if(b)openPaxManagerV24(b);
});

// Add a visible Pax Manager button to booking detail modal after it opens.
// This wraps the existing openRecord only for bookings.
const _v24OpenRecordBase = openRecord;
openRecord = async function(name,id,edit=false){
  if(name!=='bookings') return _v24OpenRecordBase(name,id,edit);
  const result=await _v24OpenRecordBase(name,id,edit);
  if(id){
    const b=state.cache.bookings.find(x=>x.id===id);
    if(b){
      setTimeout(()=>{
        const footer=$('#modalFooter');
        if(footer && !footer.querySelector('[data-v24-pax-manager]')){
          const btn=document.createElement('button');
          btn.className='btn btn-soft';
          btn.type='button';
          btn.dataset.v24PaxManager=b.id;
          btn.textContent='Pax / Companion Codes';
          footer.insertBefore(btn,footer.firstChild);
        }
      },20);
    }
  }
  return result;
};

// Also hook into V2.1 typed booking edit modal if present.
const _v24OpenBookingV21 = typeof openBookingV21==='function' ? openBookingV21 : null;
if(_v24OpenBookingV21){
  openBookingV21 = async function(type,id=null){
    const result=await _v24OpenBookingV21(type,id);
    if(id){
      const b=state.cache.bookings.find(x=>x.id===id);
      if(b){
        setTimeout(()=>{
          const footer=$('#modalFooter');
          if(footer && !footer.querySelector('[data-v24-pax-manager]')){
            const btn=document.createElement('button');
            btn.className='btn btn-soft';
            btn.type='button';
            btn.dataset.v24PaxManager=b.id;
            btn.textContent='Pax / Companion Codes';
            footer.insertBefore(btn,footer.firstChild);
          }
        },20);
      }
    }
    return result;
  };
}
